#!/usr/bin/env bash

case $* in
    "init" )
        cp -n platform/config/local.js.sample platform/config/local.js
        cp -n platform/migrations/config.json.sample platform/migrations/config.json
        ;;
    "deploy" )
        git pull
        docker-compose down
        touch var/docker/logs/app.log
        chmod 777 var/docker/logs/app.log
        touch var/docker/logs/sql.log
        chmod 777 var/docker/logs/sql.log
        docker-compose up -d
        ;;
    "start" )
        touch var/docker/logs/app.log
        chmod 777 var/docker/logs/app.log
        touch var/docker/logs/sql.log
        chmod 777 var/docker/logs/sql.log
        docker-compose up -d
        ;;
    "stop" )
        docker-compose down
        ;;
    "shell" )
        docker exec -it emkc /bin/bash
        ;;
    "rebuild" )
        docker-compose build
        ;;
    "npm" )
        docker exec -it emkc bash -c 'cd /opt/emkc/platform; npm install'
        ;;
    "mysql" )
        docker exec -it emkc bash -c 'mysql -hmysql -uroot -proot -Demkc'
        ;;
    "migrate" )
        docker exec -it emkc bash -c 'cd /opt/emkc/platform/migrations; bmig migrate'
        ;;
    "rollback" )
        docker exec -it emkc bash -c 'cd /opt/emkc/platform/migrations; bmig rollback'
        ;;
    "tail" )
        tail -f ./var/docker/logs/*
        ;;
    * )
        echo 'emkc control, usage: emkc [command]'
        echo ''
        echo 'init       initialize env specific config files'
        echo 'start      start the emkc docker container'
        echo 'stop       stop the emkc docker container'
        echo 'shell      start a shell in the docker container'
        echo 'rebuild    rebuild emkc from scratch'
        echo 'npm        update node modules'
        echo 'mysql      login to mysql'
        echo 'migrate    run the pending database migrations'
        echo 'rollback   rollback one database migration'
        echo 'tail       watch app and db logs'
        exit 1
esac
