#!/usr/bin/env bash

if [[ $@ == *--watch* ]]; then
    node_modules/.bin/gulp watch &
else
    node_modules/.bin/gulp
fi

pid=
function start {
    node engineerman.js &
    pid=$!
}

while true; do
    start
    inotifywait -qq -r --excludei '(node_modules|public|resources)' -e modify,create,delete,move .
    echo "killing $pid and restarting..."
    kill -15 $pid
    wait $pid
done
