#!/usr/bin/env bash

if [[ $@ == *--watch* ]]; then
    node_modules/.bin/gulp watch &
else
    node_modules/.bin/gulp
fi

node_modules/.bin/supervisor --extensions 'js,twig' --ignore 'node_modules,public,resources' engineerman.js
