#!/usr/bin/env bash

if [[ $@ == *--watch* ]]; then
    node_modules/.bin/gulp watch &
else
    node_modules/.bin/gulp
fi

supervisor --extensions 'js,twig' --ignore 'node_modules' --ignore 'assets' engineerman.js
